wscs-deployment:
  image:
    tag: "latest"
wscs-b-deployment:
  image:
    tag: "latest"
wsnodejs-deployment:
  image:
    tag: "edf6dff"
wsnodejs-b-deployment:
  image:
    tag: "master"
jenkinscd-framework-deployment:
  image:
    tag: "sha256:581df60cd80aec1702178a4fe25fcffc6de1567a08913e0ae71abc5a056299a6"
