wscs-deployment:
  image:
    tag: "latest"
wscs-b-deployment:
  image:
    tag: "latest"
wsnodejs-deployment:
  image:
    tag: "edf6dff"
wsnodejs-b-deployment:
  image:
    tag: "master"
jenkinscd-framework-deployment:
  image:
    tag: "sha256:91e4bccd81def7f5d733f591466e36bb6c21194821a1f5396b6a589d71912505"
